# Generated by Django 2.1.7 on 2019-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnz',
            name='type_of_vnz',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vnz',
            name='post_index',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
