# Generated by Django 2.1.7 on 2019-04-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0002_auto_20190415_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnz',
            name='subordination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
