# Generated by Django 2.1.7 on 2019-04-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0003_vnz_subordination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnz',
            name='subordination',
        ),
        migrations.AlterField(
            model_name='vnz',
            name='private',
            field=models.CharField(max_length=20),
        ),
    ]
