# Generated by Django 2.1.7 on 2019-04-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0004_auto_20190416_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnz',
            name='phone_number',
            field=models.CharField(max_length=40),
        ),
    ]
