# Generated by Django 2.1.7 on 2019-04-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0006_remove_vnz_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnz',
            name='post_index',
            field=models.PositiveIntegerField(),
        ),
    ]
