# Generated by Django 2.1.7 on 2019-04-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0008_auto_20190416_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnz',
            name='post_index',
            field=models.CharField(max_length=5),
        ),
    ]
