# Generated by Django 2.1.7 on 2019-04-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0011_auto_20190416_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnz',
            name='rector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vnz',
            name='web_site',
            field=models.CharField(max_length=100),
        ),
    ]
