# Generated by Django 2.1.7 on 2019-04-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0014_auto_20190416_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnz',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vnz',
            name='post_index',
        ),
        migrations.RemoveField(
            model_name='vnz',
            name='private',
        ),
        migrations.RemoveField(
            model_name='vnz',
            name='rector',
        ),
        migrations.RemoveField(
            model_name='vnz',
            name='type_of_vnz',
        ),
        migrations.RemoveField(
            model_name='vnz',
            name='web_site',
        ),
    ]
