# Generated by Django 2.1.7 on 2019-04-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0017_auto_20190421_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='step',
            field=models.CharField(choices=[('B', 'Бакалавр'), ('M', 'Магістр')], default='B', max_length=10),
        ),
    ]
