# Generated by Django 2.1.7 on 2019-04-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0020_remove_specialty_coef_of_mark_of_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='vnz',
            field=models.ManyToManyField(to='abiturients.VNZ'),
        ),
    ]
