# Generated by Django 2.1.7 on 2019-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0022_auto_20190423_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='name_of_specialty',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_of_subject',
            field=models.CharField(max_length=250),
        ),
    ]
