# Generated by Django 2.1.7 on 2019-05-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0024_auto_20190508_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='students',
            field=models.ManyToManyField(to='abiturients.Abiturient_Statement'),
        ),
    ]
