# Generated by Django 2.1.7 on 2019-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0025_specialty_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturient_statement',
            name='username',
            field=models.CharField(max_length=80),
        ),
    ]
