# Generated by Django 2.1.7 on 2019-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0026_auto_20190509_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturient_statement',
            name='vnzs',
            field=models.ManyToManyField(to='abiturients.VNZ'),
        ),
    ]
